url: http://www.hopeincentives.org

# Site settings
title: Hope Incentives
logo: logo.png
email: info@hopeincentives.org
description: "Data driven compassion"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 66cc99
  secondary: 66dd99
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Maclen Zilber
  pic: 1
  position: The Policy Wonk
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: stack-overflow
  #     url: #


- name: Bryce Farrington
  pic: 2
  position: The Economist
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: google-plus
  #     url: #

- name: Peter DePaulo
  pic: 3
  position: The Tech Bro
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: linkedin
  #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 5434 Carlton Way
  - line: Los Angeles, CA 90027

# Build settings
markdown: kramdown
permalink: pretty